# Automatically open MPV as a floating window, centered, with size 800x600
for_window [app_id="mpv"] floating enable, resize set 800 600, move position center
for_window [app_id="io.mpv.Mpv"] floating enable, resize set 800 600, move position center
for_window [class="mpv"] floating enable, resize set 800 600, move position center
for_window [class="Mpv"] floating enable, resize set 800 600, move position center
