# Custom Idle and Lock configuration for Sway
#
# Locks the screen after 300 seconds (5 minutes) of inactivity,
# and turns off the display 60 seconds (1 minute) after locking.
#
# Custom lock command points to our lock-screen.sh script.

set $lock_cmd /var/home/bmo/.local/bin/lock-screen.sh

exec LT=600 ST=60 SLT=1200 && \
    swayidle -w \
        timeout $LT '$lock_cmd' \
        timeout $((LT + ST)) 'swaymsg "output * power off"' \
                      resume 'swaymsg "output * power on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power on"'  \
        timeout $((LT + SLT)) 'systemctl suspend' \
        before-sleep '/var/home/bmo/.local/bin/vpn-control.sh down; $lock_cmd' \
        after-resume 'systemctl --user restart wireplumber pipewire-pulse kanshi; swaymsg "output * power on"; /var/home/bmo/.local/bin/vpn-control.sh up &' \
        lock '$lock_cmd' \
        unlock '/var/home/bmo/.local/bin/vpn-control.sh up'
