# VPN Autostart
exec /var/home/bmo/.local/bin/vpn-control.sh up

# Battery Notifier Autostart
exec /var/home/bmo/.local/bin/battery-notifier.sh

# Clipboard Watcher Daemon
exec /var/home/bmo/.local/bin/clip-watch.sh

# CopyQ Clipboard Manager
exec flatpak run com.github.hluk.copyq --start-server

# Workspace 1: Terminal Autostart
assign [app_id="Alacritty-Autostart"] workspace number 1
assign [class="Alacritty-Autostart"] workspace number 1
exec alacritty --class Alacritty-Autostart

# Workspace 2: Browser Autostart
assign [app_id="chromium-browser"] workspace number 2
assign [class="chromium-browser"] workspace number 2
exec chromium-browser

# Waybar Autostart
# exec waybar

