# Настройки отображения LocalSend
# Запуск в плавающем режиме, размер 800x600, размещение по центру экрана
for_window [app_id="(?i)localsend"] floating enable, resize set 800 600, move position center
for_window [class="(?i)localsend"] floating enable, resize set 800 600, move position center
