# Assign LibreOffice Writer to workspace 6 and open it in fullscreen
assign [app_id="writer"] workspace number 6
assign [class="writer"] workspace number 6
assign [class="Writer"] workspace number 6
assign [app_id="Writer"] workspace number 6

for_window [app_id="writer"] workspace number 6, fullscreen enable
for_window [class="writer"] workspace number 6, fullscreen enable
for_window [class="Writer"] workspace number 6, fullscreen enable
for_window [app_id="Writer"] workspace number 6, fullscreen enable
