theme = "custom"

[editor]
line-number = "relative"
auto-format = false
scrolloff = 5
color-modes = true
bufferline = "never"
popup-border = "all"
end-of-line-diagnostics = "disable"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.statusline]
left = ["mode", "selections", "position", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "workspace-diagnostics", "spinner", "file-encoding", "version-control"]
separator = " │ "
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
display-messages = true
display-inlay-hints = false
auto-signature-help = false

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"


[editor.soft-wrap]
enable = true
wrap-indicator = "↪ "

[keys.normal]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
tab = ":buffer-next"
S-tab = ":buffer-previous"

[keys.select]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
